version: "3.6"
services:
  pytorch-notebook:
    build: .
    image: tm95mon/pytorch2:latest
    container_name: pytorch_notebook
    ports: 
      - 8888:8888
      - 5000:5000
      - 6006:6006
    volumes: 
      - "$PWD:/workspace"
      - "$EXTERNAL_STORAGE:/ext_data"

    restart: always
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=letmein

    user: root
    privileged: true
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]